version: "3.0"
services:
  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:latest
    container_name: web
    ports:
      - 80:80
    volumes:
      - prestashop_web:/var/www/html
    restart: always
    environment:
      - PRESTASHOP_DB_HOST=db
      - PRESTASHOP_DB_USER=userps
      - PRESTASHOP_DB_PASSWORD=passwordps
      - PRESTASHOP_DB_NAME=bdps
      
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      -MYSQL_ROOT_PASSWORD=rootps
      -MYSQL_DATABASE=dbps
      -MYSQL_USER=prestashop
      -MYSQL_PASSWORD=prestashop
      
volumes:
  db_data: {}
  prestashop_web: {}